sudo: required
language: bash
services:
  - docker
script:
  - docker build -t keboola/orchestrator-cli .
  - docker run --rm keboola/orchestrator-cli
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
